
package com.ykren.fastdfs.event;

public enum ProgressEventType {

    /**
     * Transfer events.
     */
    REQUEST_BYTE_TRANSFER_EVENT,
    TRANSFER_STARTED_EVENT, TRANSFER_COMPLETED_EVENT, TRANSFER_FAILED_EVENT, TRANSFER_CANCELED_EVENT,
    TRANSFER_PART_STARTED_EVENT, TRANSFER_PART_COMPLETED_EVENT, TRANSFER_PART_FAILED_EVENT
}
